name: PlayerShop
description: Only a simple shop plugin.
version: 1.0
api-version: 1.8
author: zPedroo_
main: com.zpedroo.playershop.PlayerShop
depend: [ProtocolLib, HolographicDisplays, MultiEconomy, PlotSquared]
commands:
  createshop:
    aliases: [criarloja]